parameters:
    # Blogger contact email address
    blogger_blog.emails.contact_from_email: enquiries@symblog.yourdomain.tld
    blogger_blog.emails.contact_to_email: contact@email.com
    # Blogger max latest comments
    blogger_blog.comments.latest_comment_limit: 10

sonata_intl:
    timezone:
        # default timezone used as fallback
        default: Europe/Paris

        # locale specific overrides
        locales:
            fr: Europe/Paris
            en_UK: Europe/London

